@startuml
left to right direction
actor "Asset Manager" as am
actor "ISO" as iso #blue
actor "All Users" as user
rectangle Asset-Management {
  usecase "Create an Asset" as UC1
  usecase "Update an Asset" as UC2
  usecase "Assign Asset to User" as UC3
  usecase "View all assets" as UC4
  usecase "Request Asset" as UC5
  usecase "Approve/Reject a Request" as UC6
}
iso -[#blue]-> UC1
iso -[#blue]-> UC2
am --> UC1
am --> UC2
am --> UC3
am --> UC6
user --> UC4
user --> UC5
UC5 <. UC3 : <<uses>>
UC6 ..> UC5 : <<includes>>
@enduml