@startuml
left to right direction
actor "Asset Manager" as am
actor "ISO" as iso
rectangle Asset-Management {
  usecase "Create a Data-Scope" as UC1
  usecase "Update a Data-Scope" as UC2
  usecase "Assign a Data-Scope" as UC3
}
iso --> UC1
iso --> UC2
am --> UC1
am --> UC2
am --> UC3
@enduml