@startuml
left to right direction
actor "Data-Custodian" as dc #green
actor "ISO" as iso #blue
actor "ISO" as iso2 #blue
actor "DISO" as diso #red
rectangle Compliance-Matrix {
  usecase "Create a Compliance-Matrix" as UC1
  usecase "Update a Compliance-Matrix" as UC2
  usecase "Revoke a Compliance-Matrix" as UC3
  usecase "Assign Tasks to Users" as UC4
  usecase "Action Task to User" as UC5
}
iso -[#blue]-> UC1
iso -[#blue]-> UC2
iso -[#blue]-> UC3
iso -[#blue]-> UC4
diso -[#red]-> UC1
diso -[#red]-> UC2
diso -[#red]-> UC3
diso -[#red]-> UC4
UC5 -[#green]-> dc
UC5 -[#blue]-> iso2
@enduml