@startuml
left to right direction
actor "Data Custodian" as fc
rectangle Data-Scopes {
  usecase "Create a Data-Scope" as UC1
  usecase "Update a Data-Scope" as UC2
  usecase "Revoke a Data-Scope" as UC3
  usecase "Action Task within Data-Scope" as UC4
}
fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
@enduml