@startuml
left to right direction
actor "ISO/DISO" as iso
actor "Data Custodian" as dc
actor "User" as user
rectangle Risks-and-Findings{
usecase "Create Risk Task" as UC1
usecase "Update Risk Task" as UC2
usecase "Approve/Deny Risk Task" as UC3
usecase "Review Risk Task" as UC4
usecase "Close Risk Task" as UC5
usecase "Assign Risk Task to User" as UC6
usecase "Submit Risk Task" as UC7
}
UC4 .> UC5 : <<uses>>
iso -[#green]-> UC1
dc -[#blue]-> UC1
iso -[#green]-> UC6
UC6 ---> user
iso -[#green]-> UC2
dc -[#blue]-> UC2
iso -[#green]-> UC3
iso -[#green]-> UC4
iso -[#green]-> UC5
UC2 --> user : notify
user --> UC7
dc -[#blue]-> UC6
UC7 .> UC4 : <<uses>>
@enduml