@startuml
skinparam backgroundColor #1e1e1e
left to right direction
actor "Any User" as au #black;text:white;line:white
actor "Any User" as au2 #black;text:white;line:white
actor "ISO" as iso #blue;text:white;line:white
actor "DISO" as diso #red;text:white;line:white
actor "DISO" as diso2 #red;text:white;line:white
actor "Support Entity" as se #green;text:white;line:white
rectangle Support-Requests #text:white;line.bold;line:white {
  usecase "Create a Support Request" as UC1 #black;text:white;line.bold;line:white
  usecase "Update a Support Request" as UC2 #black;text:white;line.bold;line:white
  usecase "Assign Support Request" as UC3 #black;text:white;line.bold;line:white
  usecase "Action Support Request" as UC4 #black;text:white;line.bold;line:white
}
au -[#black]-> UC1
UC4 -[#black]-> au2
iso -[#blue]-> UC2
iso -[#blue]-> UC3
diso -[#red]-> UC2
diso -[#red]-> UC3
UC4 -[#red]-> diso2
UC4 -[#green]-> se
UC3 <. (UC4) #line:white;text:white : <<uses>>
@enduml