import logo from './logo.svg';
import './App.css';

function App() {
  return (
      <div className="v36_473">
        <span className="v36_474">INFOSAFE</span>
        <span className="v36_475">INFOSAFE</span>
        <span className="v36_476">INFOSAFE</span>
        <span className="v36_477">INFOSAFE</span>
        <span className="v36_478">INFOSAFE</span>
        <span className="v36_479">INFOSAFE</span>
        <span className="v36_480">INFOSAFE</span>
        <span className="v36_481">INFOSAFE</span>
        <span className="v36_482">INFOSAFE</span>
        <span className="v36_483">INFOSAFE</span>
        <span className="v36_484">INFOSAFE</span>
        <span className="v36_485">INFOSAFE</span>
        <span className="v36_486">INFOSAFE</span>
        <span className="v36_487">INFOSAFE</span>
        <span className="v36_488">INFOSAFE</span>
        <span className="v36_489">INFOSAFE</span>
        <span className="v36_490">INFOSAFE</span>
        <span className="v36_491">INFOSAFE</span>
        <span className="v36_492">INFOSAFE</span>
        <span className="v36_493">INFOSAFE</span>
        <span className="v36_494">INFOSAFE</span>
        <span className="v36_495">INFOSAFE</span>
        <span className="v36_496">INFOSAFE</span>
        <span className="v36_497">INFOSAFE</span>
        <span className="v36_498">INFOSAFE</span>
        <span className="v36_499">INFOSAFE</span>
        <span className="v36_500">INFOSAFE</span>
        <span className="v36_501">INFOSAFE</span>
        <span className="v36_502">INFOSAFE</span>
        <span className="v36_503">INFOSAFE</span>
        <span className="v36_504">INFOSAFE</span>
        <span className="v36_505">INFOSAFE</span>
        <span className="v36_506">INFOSAFE</span>
        <span className="v36_507">INFOSAFE</span>
        <span className="v36_508">INFOSAFE</span>
        <span className="v36_509">INFOSAFE</span>
        <span className="v36_510">INFOSAFE</span>
        <span className="v36_511">INFOSAFE</span>
        <span className="v36_512">INFOSAFE</span>
        <span className="v36_513">INFOSAFE</span>
        <span className="v36_514">INFOSAFE</span>
        <span className="v36_515">INFOSAFE</span>
        <span className="v36_516">INFOSAFE</span>
        <span className="v36_517">INFOSAFE</span>
        <span className="v36_518">INFOSAFE</span>
        <span className="v36_519">INFOSAFE</span>
        <span className="v36_520">INFOSAFE</span>
        <span className="v36_521">INFOSAFE</span>
        <span className="v36_522">INFOSAFE</span>
        <span className="v36_523">INFOSAFE</span>
        <span className="v36_524">INFOSAFE</span>
        <span className="v36_525">INFOSAFE</span>
        <span className="v36_526">INFOSAFE</span>
        <span className="v36_527">INFOSAFE</span>
        <span className="v36_528">INFOSAFE</span>
        <span className="v36_529">INFOSAFE</span>
        <span className="v36_530">INFOSAFE</span>
        <span className="v36_531">INFOSAFE</span>
        <span className="v36_532">INFOSAFE</span>
        <span className="v36_533">INFOSAFE</span>
        <span className="v36_534">INFOSAFE</span>
        <span className="v36_535">INFOSAFE</span>
        <span className="v36_536">INFOSAFE</span>
        <span className="v36_537">INFOSAFE</span>
        <span className="v36_538">INFOSAFE</span>
        <span className="v36_539">INFOSAFE</span>
        <span className="v36_540">INFOSAFE</span>
        <span className="v36_541">INFOSAFE</span>
        <span className="v36_542">INFOSAFE</span>
        <span className="v36_543">INFOSAFE</span>
        <span className="v36_544">INFOSAFE</span>
        <span className="v36_545">INFOSAFE</span>
        <span className="v36_546">INFOSAFE</span>
        <span className="v36_547">INFOSAFE</span>
        <span className="v36_548">INFOSAFE</span>
        <span className="v36_549">INFOSAFE</span>
        <span className="v36_550">INFOSAFE</span>
        <span className="v36_551">INFOSAFE</span>
        <span className="v36_552">INFOSAFE</span>
        <span className="v36_553">INFOSAFE</span>
        <span className="v36_554">INFOSAFE</span>
        <span className="v36_555">INFOSAFE</span>
        <span className="v36_556">INFOSAFE</span>
        <span className="v36_557">INFOSAFE</span>
        <span className="v36_558">INFOSAFE</span>
        <span className="v36_559">INFOSAFE</span>
        <span className="v36_560">INFOSAFE</span>
        <span className="v36_561">INFOSAFE</span>
        <div className="v36_562"></div>
        <span className="v36_563">LOGIN</span>
        <div className="v36_564"></div>
        <div className="v36_565"></div>
        <span className="v36_566">Username</span>
        <span className="v36_567">PASSWORD</span>
        <div className="v36_568">
          <div className="name"></div>
        </div>
        <span className="v36_570">Forgot Password?</span>
      </div>
  );
}

export default App;
