package com.fragile.infosafe.tests;
// Generated by CodiumAI

import com.fragile.infosafe.primary.model.Asset;
import org.junit.Test;

import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.PersistenceException;

import static org.junit.Assert.*;

public class AssetTest {

    // Create an instance of Asset with an invalid device_type and expect a PersistenceException.
    @Test
    public void test_create_asset_with_invalid_device_type() {
        // Create an instance of Asset with an invalid device_type
        Asset asset = Asset.builder()
                .asset_name("Test Asset")
                .asset_description("Test Description")
                .status("Active")
                .availability("Available")
                .used("Not Used")
                .device_type("Invalid Device Type")
                .build();

        // Expect a PersistenceException when persisting the asset
        assertThrows(PersistenceException.class, () -> {
            EntityManager entityManager = Persistence.createEntityManagerFactory("test").createEntityManager();
            entityManager.getTransaction().begin();
            entityManager.persist(asset);
            entityManager.getTransaction().commit();
        });
    }

}