package com.fragile.infosafe.tests;
// Generated by CodiumAI

import com.fragile.infosafe.primary.model.DataScope;
import com.fragile.infosafe.primary.model.Task;
import com.fragile.infosafe.primary.model.User;
import org.junit.Test;

import java.util.Arrays;
import java.util.HashSet;

import static org.junit.Assert.*;

public class TaskTest {


    // Create a task with all fields filled
    @Test
    public void test_create_task_with_all_fields_filled() {
        Task task = Task.builder()
                .task_id(1)
                .task_name("Task 1")
                .task_description("Description 1")
                .task_status("Pending")
                .due_date("2022-01-01")
                .date_created("2021-12-01")
                .data_scope_id(DataScope.builder().data_scope_id(1).build())
                .users(new HashSet<>(Arrays.asList(User.builder().user_id(1).build())))
                .daysUntilDue(30)
                .build();

        assertEquals(1, task.getTask_id());
        assertEquals("Task 1", task.getTask_name());
        assertEquals("Description 1", task.getTask_description());
        assertEquals("Pending", task.getTask_status());
        assertEquals("2022-01-01", task.getDue_date());
        assertEquals("2021-12-01", task.getDate_created());
        assertEquals(1, task.getData_scope_id().getData_scope_id());
        assertEquals(1, task.getUsers().size());
        assertEquals(30, task.getDaysUntilDue());
    }

    // Add a user to a task
    @Test
    public void test_add_user_to_task() {
        Task task = Task.builder()
                .task_id(1)
                .task_name("Task 1")
                .users(new HashSet<>())
                .build();

        User user = User.builder()
                .user_id(1)
                .first_name("John")
                .last_name("Doe")
                .email("john.doe@example.com")
                .password("password")
                .build();

        task.getUsers().add(user);

        assertEquals(1, task.getUsers().size());
        assertTrue(task.getUsers().contains(user));
    }

    // Remove a user from a task
    @Test
    public void test_remove_user_from_task() {
        User user = User.builder()
                .user_id(1)
                .first_name("John")
                .last_name("Doe")
                .email("john.doe@example.com")
                .password("password")
                .build();

        Task task = Task.builder()
                .task_id(1)
                .task_name("Task 1")
                .users(new HashSet<>(Arrays.asList(user)))
                .build();

        task.getUsers().remove(user);

        assertEquals(0, task.getUsers().size());
        assertFalse(task.getUsers().contains(user));
    }

    // Create a task with a null data scope
    @Test
    public void test_create_task_with_null_data_scope() {
        Task task = Task.builder()
                .task_id(1)
                .task_name("Task 1")
                .data_scope_id(null)
                .build();

        assertEquals(1, task.getTask_id());
        assertEquals("Task 1", task.getTask_name());
        assertNull(task.getData_scope_id());
    }
}