@startuml
skinparam backgroundColor #1e1e1e
left to right direction
actor "ISO" as iso #blue;text:white;line:white
actor "DISO" as diso #red;text:white;line:white
actor "Sys Admin" as sa #green;text:white;line:white
rectangle Users #text:white;line.bold;line:white {
  usecase "Create a User" as UC1 #black;text:white;line.bold;line:white
  usecase "Update a User and Role" as UC2 #black;text:white;line.bold;line:white
  usecase "Revoke a User and Role" as UC3 #black;text:white;line.bold;line:white
  usecase "View all Users" as UC4 #black;text:white;line.bold;line:white
  usecase "View Selected User Details" as UC5 #black;text:white;line.bold;line:white
  usecase "Generate Unique Password" as UC6 #black;text:white;line.bold;line:white
}
iso -[#blue]-> UC1
iso -[#blue]-> UC2
iso -[#blue]-> UC3
iso -[#blue]-> UC4
iso -[#blue]-> UC5
diso -[#red]-> UC1
diso -[#red]-> UC2
diso -[#red]-> UC3
diso -[#red]-> UC4
diso -[#red]-> UC5
sa -[#green]-> UC1
sa -[#green]-> UC2
sa -[#green]-> UC3
sa -[#green]-> UC4
sa -[#green]-> UC5
UC1 <. (UC6) #line:white;text:white : <<uses>>
@enduml