name: Cypress Tests
on: [push, pull_request]
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Cypress dependencies
        run: npm install

      - name: Start backend and frontend applications
        run: npm run frontend

      - name: Wait for applications to start
        run: sleep 45  # Adjust the duration based on how long it takes for your applications to start

      - name: Run Cypress tests
        run: npx cypress run