name: Linter
on: [push, pull_request]
jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Run Linter
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: main
                  VALIDATE_ALL_CODEBASE: false
                  VALIDATE_TYPESCRIPT_ES: true
                  VALIDATE_SQL: true
                  VALIDATE_STATES: true
                  VALIDATE_JAVASCRIPT_STANDARD: true
                  VALIDATE_JAVASCRIPT_ES: true
                  VALIDATE_HTML: true
                  VALIDATE_GITHUB_ACTIONS: true
                  VALIDATE_CSS: true
                  VALIDATE_JAVA: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
