name: React Front-End Unit Testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Install required deps for action
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend/infosafe_frontend

      # Finally, run our tests
      - name: Execute Unit Tests
        run: npm run test
        working-directory: frontend/infosafe_frontend

      # Codecov report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}